package io.jyri.dictator.model

/** Languages supported by the vendored whisper.cpp multilingual model. */
enum class SpokenLanguage(
    val whisperCode: String,
    val displayName: String,
) {
    ENGLISH("en", "English"),
    CHINESE("zh", "Chinese"),
    GERMAN("de", "German"),
    SPANISH("es", "Spanish"),
    RUSSIAN("ru", "Russian"),
    KOREAN("ko", "Korean"),
    FRENCH("fr", "French"),
    JAPANESE("ja", "Japanese"),
    PORTUGUESE("pt", "Portuguese"),
    TURKISH("tr", "Turkish"),
    POLISH("pl", "Polish"),
    CATALAN("ca", "Catalan"),
    DUTCH("nl", "Dutch"),
    ARABIC("ar", "Arabic"),
    SWEDISH("sv", "Swedish"),
    ITALIAN("it", "Italian"),
    INDONESIAN("id", "Indonesian"),
    HINDI("hi", "Hindi"),
    FINNISH("fi", "Finnish"),
    VIETNAMESE("vi", "Vietnamese"),
    HEBREW("he", "Hebrew"),
    UKRAINIAN("uk", "Ukrainian"),
    GREEK("el", "Greek"),
    MALAY("ms", "Malay"),
    CZECH("cs", "Czech"),
    ROMANIAN("ro", "Romanian"),
    DANISH("da", "Danish"),
    HUNGARIAN("hu", "Hungarian"),
    TAMIL("ta", "Tamil"),
    NORWEGIAN("no", "Norwegian"),
    THAI("th", "Thai"),
    URDU("ur", "Urdu"),
    CROATIAN("hr", "Croatian"),
    BULGARIAN("bg", "Bulgarian"),
    LITHUANIAN("lt", "Lithuanian"),
    LATIN("la", "Latin"),
    MAORI("mi", "Maori"),
    MALAYALAM("ml", "Malayalam"),
    WELSH("cy", "Welsh"),
    SLOVAK("sk", "Slovak"),
    TELUGU("te", "Telugu"),
    PERSIAN("fa", "Persian"),
    LATVIAN("lv", "Latvian"),
    BENGALI("bn", "Bengali"),
    SERBIAN("sr", "Serbian"),
    AZERBAIJANI("az", "Azerbaijani"),
    SLOVENIAN("sl", "Slovenian"),
    KANNADA("kn", "Kannada"),
    ESTONIAN("et", "Estonian"),
    MACEDONIAN("mk", "Macedonian"),
    BRETON("br", "Breton"),
    BASQUE("eu", "Basque"),
    ICELANDIC("is", "Icelandic"),
    ARMENIAN("hy", "Armenian"),
    NEPALI("ne", "Nepali"),
    MONGOLIAN("mn", "Mongolian"),
    BOSNIAN("bs", "Bosnian"),
    KAZAKH("kk", "Kazakh"),
    ALBANIAN("sq", "Albanian"),
    SWAHILI("sw", "Swahili"),
    GALICIAN("gl", "Galician"),
    MARATHI("mr", "Marathi"),
    PUNJABI("pa", "Punjabi"),
    SINHALA("si", "Sinhala"),
    KHMER("km", "Khmer"),
    SHONA("sn", "Shona"),
    YORUBA("yo", "Yoruba"),
    SOMALI("so", "Somali"),
    AFRIKAANS("af", "Afrikaans"),
    OCCITAN("oc", "Occitan"),
    GEORGIAN("ka", "Georgian"),
    BELARUSIAN("be", "Belarusian"),
    TAJIK("tg", "Tajik"),
    SINDHI("sd", "Sindhi"),
    GUJARATI("gu", "Gujarati"),
    AMHARIC("am", "Amharic"),
    YIDDISH("yi", "Yiddish"),
    LAO("lo", "Lao"),
    UZBEK("uz", "Uzbek"),
    FAROESE("fo", "Faroese"),
    HAITIAN_CREOLE("ht", "Haitian Creole"),
    PASHTO("ps", "Pashto"),
    TURKMEN("tk", "Turkmen"),
    NYNORSK("nn", "Nynorsk"),
    MALTESE("mt", "Maltese"),
    SANSKRIT("sa", "Sanskrit"),
    LUXEMBOURGISH("lb", "Luxembourgish"),
    MYANMAR("my", "Myanmar"),
    TIBETAN("bo", "Tibetan"),
    TAGALOG("tl", "Tagalog"),
    MALAGASY("mg", "Malagasy"),
    ASSAMESE("as", "Assamese"),
    TATAR("tt", "Tatar"),
    HAWAIIAN("haw", "Hawaiian"),
    LINGALA("ln", "Lingala"),
    HAUSA("ha", "Hausa"),
    BASHKIR("ba", "Bashkir"),
    JAVANESE("jw", "Javanese"),
    SUNDANESE("su", "Sundanese"),
    CANTONESE("yue", "Cantonese"),
    ;

    companion object {
        const val MAX_SELECTED_LANGUAGES = 4

        fun fromWhisperCode(code: String): SpokenLanguage? =
            entries.firstOrNull { it.whisperCode == code }
    }
}
